# -*- coding: utf-8 -*-
"""Разделы аудитов с выставок для index.html.
Файл генерируется build_all.py — правьте карточки клиентов, а не его."""

SECTIONS = [
  ('Аудиты с выставки · Мир детства · 16–19.09.2026', [
    ('polesie-toys.html', 'Полесье (Polesie Toys)', 'Производство пластмассовых игрушек · polesie-toys.com'),
    ('simbat.html', 'СИМБАТ', 'Создание и дистрибуция брендов игрушек · igr.ru'),
    ('brick-labs.html', 'BRICK LABS', 'Конструкторы · группа Inventive · bricklabs.ru'),
    ('inventive-toys.html', 'Inventive Toys', 'Оптовая дистрибуция игрушек · inventive-toys.ru'),
    ('ural-toys.html', 'URAL TOYS', 'Торгово-производственная компания · игрушки · ural.toys'),
    ('paremo.html', 'PAREMO', 'Развивающие игрушки и детская мебель'),
    ('nikastyle.html', 'Nikastyle', 'Детская функциональная одежда · nikastyle.ru'),
    ('miasin.html', 'Miasin', 'Одежда и аксессуары для подростков · miasinopt.ru'),
    ('deloras.html', 'DELORAS', 'Коляски, автокресла, стульчики для кормления · deloras.ru'),
    ('tzar-elka.html', 'Царь Ёлка', 'Искусственные ёлки и новогодний декор · tzar-elka.ru'),
    ('robotime.html', 'ROBOTIME / Rolife', 'Деревянные конструкторы и DIY-наборы · robotime.com'),
  ]),
  ('Аудиты с выставки · выставка, сентябрь 2026', [
    ('samson-opt.html', 'Самсон', 'Опт канцелярских, офисных и хозяйственных товаров · samsonopt.ru'),
  ]),
  ('Аудиты с выставки · World Food Moscow · 15–18.09.2026', [
    ('priokskoe.html', 'Приокское (Приокская икра)', 'Осетровое рыбоводство, икра · Алексин'),
    ('fitness-food.html', 'Фитнес Фуд (Bombbar, Snaq Fabriq, Chikalab)', 'Спортивное питание и ЗОЖ-снеки · bombbar.ru'),
    ('bombbar-horeca.html', 'Бомббар · направление HoReCa', 'Спортивное питание и ЗОЖ-снеки · HoReCa · bombbar.ru'),
    ('tomer.html', 'TOMER', 'Шоколад, конфеты, батончики, СТМ · tomerchoco.ru'),
    ('libertad-choco.html', 'Libertad', 'Производство и опт шоколада · Химки · domchoco.ru'),
    ('meco-drinks.html', 'Meco', 'Холодный чай из Китая · импорт и дистрибуция · Meco.Moscow'),
    ('neo-produkt.html', 'НЕО Продукт', 'Молочные продукты и сыры · neoproduct.ru'),
    ('jfk-international.html', 'JFK International', 'Кофе, чай, рис, специи · экспорт из Индии · jfk.in'),
  ]),
  ('Выход на рынок РФ · China', [
    ('planet-toys.html', 'Planet Toys', 'toy manufacturing and export · —'),
    ('eleph-bunny.html', 'Eleph Bunny', 'toy manufacturing · elephbunny.com'),
    ('toycity.html', 'TOYCITY', 'collectible toys and art toys · —'),
    ('lecai-toys.html', 'Rainbow Bridge Clay', 'modelling clay, kinetic sand and DIY sets · —'),
    ('lianyue.html', 'LIANYUE', 'agricultural produce and fresh fruit · —'),
    ('primum-candy.html', 'Soft Lollipop Candy', 'lollipops and confectionery · swlpfood.com'),
    ('lechao.html', 'Lechao', 'confectionery · lechao.en.alibaba.com'),
    ('changbaoer.html', 'Changbaoer Food', 'lollipops, jelly sweets and candy toys · —'),
    ('tianchao.html', 'Tianchao Food', 'jelly desserts and drinks · —'),
    ('hicey.html', 'Hicey', 'ice cream, desserts and snacks · hiceyicecream.com'),
  ]),
  ('Выход на рынок РФ · Ecuador', [
    ('levexport.html', 'LEVEXPORT', 'banana and fresh fruit export · levexport.ec'),
  ]),
  ('Выход на рынок РФ · Malaysia', [
    ('jacker-ofi.html', 'Jacker', 'savoury snacks · ofi.com.my'),
  ]),
  ('Выход на рынок РФ · Vietnam', [
    ('vinut.html', 'VINUT', 'juices and soft drinks · vinut.com.vn'),
    ('tan-do.html', 'TAN DO', 'soft drinks · tandobeverage.com'),
  ]),
  ('Выход на рынок РФ · India', [
    ('adept-impex.html', 'Adept Impex', 'dried herbs and flowers for herbal and green tea · adeptimpex.com'),
    ('akshaj-foods.html', 'Akshaj Foods', 'fruit purees and concentrates, IQF fruit and vegetables, foxnuts · akshajfoods.co.in'),
    ('al-faiz.html', 'Al Faiz Enterprises', 'frozen halal buffalo meat · alfaizenterprises.com'),
    ('biowin-agro.html', 'Biowin Agro Research', 'green coffee, spices and freeze-dried products · biowinkerala.com'),
    ('essar-exports.html', 'Essar Exports', 'fresh and frozen fruit and vegetables · essarexports.com'),
    ('farm-to-table.html', 'Farm To Table Trading', 'fresh fruit and vegetables · —'),
    ('gurukrupa.html', 'Gurukrupa Corporation', 'fresh fruit and vacuum-packed corn · gkcfresh.com'),
    ('jadli-foods.html', 'Jadli Foods', 'fruit purees and concentrates, pastes and IQF products · jadlifoods.com'),
    ('natures-partner.html', "Nature's Partner", 'canned sweet corn and gherkins · naturespartnerindia.com'),
    ('natural-dehy.html', 'Natural Dehydrated Veg', 'dehydrated onion and garlic, IQF sweet corn · naturaldehydration.com'),
    ('olitia.html', 'Olitia', 'olive leaf tea and herbal wellness infusions · olitia.com'),
    ('seeds-grains.html', 'Seeds & Grains India', 'sesame, pulses, spices, chia, quinoa and superfoods · seeds-grains.com'),
    ('shanti-veer.html', 'Shanti Veer Agro', 'basmati and non-basmati rice, peanuts, sesame and chia · shantiveeragro.com'),
    ('sunanda-foods.html', 'Sunanda Foods', 'spices, dehydrated vegetables, guar gum and organic lines · sunandafoods.com'),
    ('punjab-markfed.html', 'Punjab Markfed · SOHNA', 'ready-to-eat canned foods, pickles, honey, mustard oil and rice · markfedpunjab.com'),
    ('vezbynature.html', 'Vezbynature', 'fruit pulps, tomato paste and IQF products · vezbynature.com'),
    ('daily-foodzz.html', 'Daily Foodzz', 'frozen vegetables, snacks, french fries and corn · dailyfoodzz.com'),
    ('yms-international.html', 'YMS International', 'fried and dehydrated onion and garlic · ymsinternational.com'),
    ('brewsaga.html', 'Brewsaga Coffee', 'instant coffee, private label and roasting · brewsagacoffee.com'),
    ('ccl-products.html', 'CCL Products · Continental Coffee', 'instant coffee — freeze dried, agglomerated and spray dried — and filter coffee · continental.coffee'),
    ('chikoff.html', 'Chikoff Trading', 'instant and green coffee, chicory blends and capsules · chikoff.com'),
    ('highrange-coffee.html', 'Highrange Coffee', 'green coffee beans · highrangecoffee.com'),
    ('kape-kapi.html', 'Kape Kapi & Exports', 'green, roasted and instant coffee · kapekapi.com'),
    ('sln-coffee.html', 'SLN Coffee', 'instant coffee · slncoffee.com'),
    ('smoky-falls.html', 'Smoky Falls Tribe Coffee', 'roasted Arabica and Robusta coffee · —'),
    ('iopepc.html', 'IOPEPC', 'export promotion council for Indian oilseeds and produce · iopepc.org'),
  ]),
]
